//! Prometheus instrumentation helper shared by every tool's backend.
//!
//! Wraps `axum-prometheus` so a tool only has to call [`metrics_layer`] and
//! merge the returned router in, rather than each tool hand-rolling its own
//! `/metrics` endpoint. The corresponding `ServiceMonitor` that tells the
//! cluster's Prometheus Operator to scrape this path is generated by the
//! Helm library chart (`deploy/charts/tool-library/templates/servicemonitor.yaml`)
//! whenever a tool sets `monitoring.enabled: true` in its values -- see
//! `docs/observability.md`.

use axum::routing::get;
use axum::Router;
use axum_prometheus::PrometheusMetricLayer;

/// Returns a `tower` layer that records HTTP request metrics (latency,
/// status codes, in-flight count) for every route it wraps, plus a small
/// router exposing them at `/metrics` in Prometheus text format.
///
/// Typical use in a tool's backend:
///
/// ```ignore
/// let (metrics_layer, metrics_router) = metrics_adapter::metrics_layer();
/// let app = Router::new()
///     .route("/health", get(health))
///     .merge(metrics_router)
///     .layer(metrics_layer);
/// ```
pub fn metrics_layer<S>() -> (PrometheusMetricLayer<'static>, Router<S>)
where
    S: Clone + Send + Sync + 'static,
{
    let (layer, handle) = PrometheusMetricLayer::pair();
    let router = Router::new().route(
        "/metrics",
        get(move || {
            let handle = handle.clone();
            async move { handle.render() }
        }),
    );
    (layer, router)
}
