apiVersion: v2
name: {{project-name}}
description: "{{description}}"
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: tool-library
    version: 0.1.0
    repository: "file://../charts/tool-library"
